### ISSUE TITLE
Configure nginx security headers

### ISSUE THREAD

**Issue by iokiwi** [nzpug/chat#12]
https://securityheaders.com/?q=http%3A%2F%2Fchat.python.nz&hide=on&followRedirects=on

**Comment by dannyadair** [comment]
Oh cool. How does this compare to
https://www.ssllabs.com/ssltest/analyze.html?d=chat.python.nz&latest

**Comment by rhyven** [comment]
SSL Labs has a focus on SSL configuration. SecurityHeaders.io touches lightly on SSL, but is more concerned with other headers including things like CSP.

The Venn diagram does overlap between them - e.g. they both look at HSTS configuration. But they do have different focus.

E

--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by dannyadair** [comment]
Oh good - I shall be using that as well in the future!
No good to have a B here and an F there :)

**Comment by FelisNigelus** [comment]
Hardenize.com and urlscan.io 
Our results for python.nz 
HDNZ: https://www.hardenize.com/report/python.nz/1586313694 
URLS: https://urlscan.io/result/b0b1f7f1-8c90-446e-9488-7f3bdcafa73f

**Comment by dannyadair** [comment]
Oh good, more!
But that's python.nz == Portalbuzz. Can't fix that ourselves :)

**Comment by iokiwi** [comment]
`A+` - [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=chatserver.python.nz)
`A` - [Security Headers](https://securityheaders.com/?q=https%3A%2F%2Fchatserver.python.nz&hide=on&followRedirects=on)
